// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDyAWNM-KrtTrMBBI-nEptkpMWqb9C5WE',
    appId: '1:153116402975:web:29b26f42d7ce6e4b5cbc2a',
    messagingSenderId: '153116402975',
    projectId: 'luxury-mart2',
    authDomain: 'luxury-mart2.firebaseapp.com',
    storageBucket: 'luxury-mart2.firebasestorage.app',
    measurementId: 'G-NB9WHTY1XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7L5_kj52gdOjCESKIQOTYwgfnCLIIHcQ',
    appId: '1:153116402975:android:50ee29e6e13df5635cbc2a',
    messagingSenderId: '153116402975',
    projectId: 'luxury-mart2',
    storageBucket: 'luxury-mart2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7goKSNru3WPuS1zwFtoDBdrC4eYDLer4',
    appId: '1:153116402975:ios:042f9e08cb43b7905cbc2a',
    messagingSenderId: '153116402975',
    projectId: 'luxury-mart2',
    storageBucket: 'luxury-mart2.firebasestorage.app',
    androidClientId: '153116402975-rapdhtmq8s1dih6fssu9j6acfqfvbf7o.apps.googleusercontent.com',
    iosClientId: '153116402975-i55vqjud2pri6d7873774fub42qagecv.apps.googleusercontent.com',
    iosBundleId: 'com.example.luxuryMart',
  );

}